#!/usr/bin/env bash
# ── Cashnarok™ – Debian 12 / Proxmox LXC installer ────────────
# Run as root inside the container:  bash install.sh
# ─────────────────────────────────────────────────────────────────
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()      { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()     { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

WEBROOT="/var/www/html"
SITE_CONF="/etc/apache2/sites-available/budsjett.conf"
DB_NAME="budsjett"
DB_USER="budsjett_user"
DB_PASS="$(openssl rand -base64 20 | tr -dc 'A-Za-z0-9' | head -c 24)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo -e "${BOLD}════════════════════════════════════════${NC}"
echo -e "${BOLD}  Cashnarok™ – Installasjonsscript   ${NC}"
echo -e "${BOLD}════════════════════════════════════════${NC}"
echo ""

# ── Root check ───────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "Kjør som root: sudo bash install.sh"

# ── 1. System update + packages ──────────────────────────────────
info "Oppdaterer pakkelister…"
apt-get update -qq

info "Installerer Apache, PHP og MariaDB…"
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    apache2 \
    php \
    php-mysql \
    libapache2-mod-php \
    mariadb-server \
    openssl \
    curl
ok "Pakker installert."

# ── 2. Start / enable services ───────────────────────────────────
info "Starter og aktiverer tjenester…"
systemctl enable --now apache2  > /dev/null 2>&1
systemctl enable --now mariadb  > /dev/null 2>&1
ok "Apache og MariaDB kjører."

# ── 3. Secure MariaDB + create DB/user ───────────────────────────
info "Konfigurerer MariaDB…"

# Remove anonymous users, test db, disallow remote root
mysql -u root <<SQL
DELETE FROM mysql.user WHERE User='';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost','127.0.0.1','::1');
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
FLUSH PRIVILEGES;
SQL

# Create DB and user
mysql -u root <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\`
    CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL
ok "Database '${DB_NAME}' og bruker '${DB_USER}' opprettet."

# ── 4. Write db.php with real credentials ────────────────────────
info "Skriver db.php med databaselegitimasjon…"
cat > "${SCRIPT_DIR}/db.php" <<PHPEOF
<?php
// ── Database connection ───────────────────────────────────────
// Generated by install.sh – do NOT edit manually

define('DB_HOST', 'localhost');
define('DB_NAME', '${DB_NAME}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');

function getDB(): PDO {
    static \$pdo = null;
    if (!\$pdo) {
        \$pdo = new PDO(
            'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=utf8mb4',
            DB_USER,
            DB_PASS,
            [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES   => false,
            ]
        );
    }
    return \$pdo;
}
PHPEOF
ok "db.php skrevet."

# ── 5. Copy app files to web root ────────────────────────────────
info "Kopierer filer til ${WEBROOT}…"

# Remove default Apache page
rm -f "${WEBROOT}/index.html" 2>/dev/null || true

for f in index.html api.php db.php install.php .htaccess howto.html; do
    if [[ -f "${SCRIPT_DIR}/${f}" ]]; then
        cp "${SCRIPT_DIR}/${f}" "${WEBROOT}/${f}"
        ok "  Kopierte ${f}"
    else
        warn "  Fant ikke ${f} – hopper over."
    fi
done

# ── 6. Permissions ───────────────────────────────────────────────
info "Setter rettigheter…"
chown -R www-data:www-data "${WEBROOT}"
find "${WEBROOT}" -type f -exec chmod 640 {} \;
find "${WEBROOT}" -type d -exec chmod 750 {} \;
# db.php: readable by web server only
chmod 640 "${WEBROOT}/db.php"
ok "Rettigheter satt."

# ── 7. Apache config ─────────────────────────────────────────────
info "Konfigurerer Apache vhost…"

a2enmod rewrite > /dev/null 2>&1
a2enmod headers > /dev/null 2>&1

cat > "${SITE_CONF}" <<'APACHEEOF'
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html

    <Directory /var/www/html>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/budsjett_error.log
    CustomLog ${APACHE_LOG_DIR}/budsjett_access.log combined
</VirtualHost>
APACHEEOF

a2dissite 000-default.conf > /dev/null 2>&1 || true
a2ensite budsjett.conf      > /dev/null 2>&1

info "Starter Apache på nytt…"
systemctl restart apache2
ok "Apache startet på nytt."

# ── 8. Get container IP ──────────────────────────────────────────
CONTAINER_IP="$(hostname -I | awk '{print $1}')"

# ── Done ─────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}════════════════════════════════════════${NC}"
echo -e "${BOLD}${GREEN}  Installasjon fullført!                ${NC}"
echo -e "${BOLD}${GREEN}════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BOLD}Steg 1 – Kjør installer i nettleser:${NC}"
echo -e "  ${CYAN}http://${CONTAINER_IP}/install.php${NC}"
echo ""
echo -e "  ${BOLD}Steg 2 – Åpne appen:${NC}"
echo -e "  ${CYAN}http://${CONTAINER_IP}/${NC}"
echo ""
echo -e "  ${BOLD}Brukerveiledning:${NC}"
echo -e "  ${CYAN}http://${CONTAINER_IP}/howto.html${NC}"
echo ""
echo -e "  ${YELLOW}Databasepassord (lagret i db.php):${NC}"
echo -e "  ${DB_PASS}"
echo ""
echo -e "  ${YELLOW}NB: Åpne install.php i nettleseren din for å fullføre oppsett!${NC}"
echo ""
